version: '3'
services:
  postgres:
    image: postgres:latest

    networks:
      - synchro-net
    container_name: postgres-synchro
    volumes:
      - synchro-db:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=PostgreSQL2018
      - POSTGRES_USER=postgres
      - POSTGRES_DB=synchroHotel
  pgadmin:
    image: dpage/pgadmin4:latest

    networks:
      - synchro-net
    container_name: pgadmin
    volumes:
      - synchro-pg:/var/lib/pgadmin
    expose:
      - 15432
    ports:
      - 15432:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@teste.com
      - PGADMIN_DEFAULT_PASSWORD=admin
networks:
  synchro-net:

volumes:
  synchro-db:
  synchro-pg:
